version: 2.0
jobs:
 build:
  docker:
    - image: dolomitedex/buildcontainer:latest
  steps:
    - run: dmesg | grep -in mem

 test1:
  docker:
    - image: dolomitedex/buildcontainer:latest
  steps:
    - run: dmesg | grep -in mem

 deploy:
  docker:
    - image: dolomitedex/buildcontainer:latest
  steps:
    - run: dmesg | grep -in mem

workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build
      - test1:
          requires:
            - build
      - hold:
          type: approval
          requires:
           - test1
      - deploy:
          requires:
            - hold