version: 2

orbs:
  ccidiag:
    description: "If you're running this bad things happened"
    executors:
      default:
        description:
          Uses the basic buildpack-deps image, which has the
          prerequisites for installing heroku's CLI.
        parameters:
          data-dir:
            type: string
            default: "~/.ccidiag"
        docker:
          - image: buildpack-deps

    commands:
      versions:
        steps:
          - run: 
            command: mkdir /tmp/.ccidiag
          - run: 
            command: dpkg -l > /tmp/.ccidiag/dpkg.log
          - store_artifacts:
              path: /tm.ccidiag
              destination: ccidiag       
    jobs:
      run:
        executor: default
        steps:
          - versions

workflows:
  version: 2
  main:
    jobs:
      - ccidiag/run


