version: 2

orbs:
  ccidiag:
    description: "If you're running this bad things happened"
    commands:
      run:
        parameters:
          data-dir:
            type: string
            default: "~/.ccidiag"
        steps:
          - run: mkdir << parameters.data-dir >>
          - run: dpkg -l > << parameters.data-dir >>/dpkg.log
          - run: yarn list > << parameters.data-dir >>/yarn.log
          - run: brew list --versions > << parameters.data-dir >>/brew.log
          - run: yarn global list > << parameters.data-dir >>/yarn-global.log
          - store_artifacts:
              path: << parameters.data-dir >>
              destination: ccidiag

jobs:
  docker:
    docker:
      - image: circleci/node
    steps:
      - ccidiag/run
  machine:
    machine: true
    steps:
      - ccidiag/run
  macos:
    xcode: "9.4.0"
    steps:
      - ccidiag/run

workflows:
  version: 2
  main:
    jobs:
      - docker


