version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    # Can be used to select or ignore specific branches when not using workflows
    # https://circleci.com/docs/2.0/configuration-reference/#branches
    branches:
      ignore:
        - notmaster
        - alsonotmaster
        # RegEx is fine too
        #- notmast*
      # Must choose ignore or only. Not both!
      #only:
      #- master

    # Select the class of resources to use. Only available with docker executor.
    # Paid accounts may request this feature from their Customer Success Manager,
    # non-paid users may request to get started by sending email to support@circleci.com.
    # https://circleci.com/docs/2.0/configuration-reference/#resource_class
    resource_class:
      #  (Class) (CPU) (RAM)
      #- small	 # 1.0	2GB
      #- medium   # 2.0	4GB (default)
      #- medium+ # 3.0	6GB
      #- large	 # 4.0	8GB
      - xlarge	 # 8.0	16GB

    working_directory: ~/repo
    steps:
      - checkout

      - run: yarn install

      # run tests!
      - run: yarn test
