version: 2

jobs:
  build:
    macos:
      xcode: "9.2.0"
    environment:
      - LC_CTYPE: en_US.UTF-8
      - LANG: en_US.UTF-8
      - FL_OUTPUT_DIR: output
    steps:
      - checkout
      ruby --version