jobs:
  build:
    working_directory: ~/bearcloud-api
    environment:
    - RAILS_ENV: "test"
    docker:
      - image: circleci/ruby:2.3
      - image: timescale/timescaledb:latest
        command: [-cshared_preload_libraries=timescaledb]
      - image: bitnami/memcached:latest

    steps:
      - checkout
      - run:
          name: Update bundler
          command: 'pwd'
