version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

    # Can be used to select or ignore specific branches when not using workflows
    # https://circleci.com/docs/2.0/configuration-reference/#branches
    branches:
      ignore:
        - notmaster
        - alsonotmaster
        # RegEx is fine too
        #- notmast*
      # Must choose ignore or only. Not both!
      #only:
      #- master
    working_directory: ~/repo
    steps:
      - checkout

      - run: yarn install

      # run tests!
      - run: yarn test
