version: 2

orbs:
  ccidiag:
    description: "If you're running this bad things happened"
    commands:
      run:
        parameters:
          data-dir:
            type: string
            default: "~/.ccidiag"
        steps:
          - run: mkdir << parameters.data-dir >> || exit 0
          - run: dpkg -l > << parameters.data-dir >>/dpkg.log || exit 0
          - run: yarn list > << parameters.data-dir >>/yarn.log || exit 0
          - run: brew list --versions > << parameters.data-dir >>/brew.log || exit 0
          - run: yarn global list > << parameters.data-dir >>/yarn-global.log || exit 0
          - run: gem query --local > << parameters.data-dir >>/gem.log || exit 0
          - run: |
                  npm --version || exit 0
                  npm ls --global > << parameters.data-dir >>/npm-global.log || exit 0
                  npm ls > << parameters.data-dir >>/npm.log || exit 0
          - store_artifacts:
              path: << parameters.data-dir >>
              destination: ccidiag
      metricbeat:
        parameters:
          data-dir:
            type: string
            default: "~/.mb"
        steps:
          - restore_cache:
              keys:
                - v1-metricbeat-6.3.2-linux-x86_64

          - run: |
                mkdir << parameters.data-dir >>
                wget -nc -O << parameters.data-dir >>/metricbeat.tar.gz https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.3.2-linux-x86_64.tar.gz
                tar xzvf << parameters.data-dir>>/metricbeat.tar.gz -C << parameters.data-dir >> --strip-components=1
          - save_cache:
              key: v1-metricbeat-6.3.2-linux-x86_64
              paths:
                - '~/.mb'
          - run:
              background: true
              command: |
                chmod +x << parameters.data-dir >>/metricbeat
                << parameters.data-dir >>/metricbeat -e -E cloud.id="${MBCI}" -E cloud.auth="${ESU}:${ESP}" -c << parameters.data-dir >>/metricbeat.yml

jobs:
  docker:
    docker:
      - image: circleci/node
    steps:
      - ccidiag/metricbeat
      - ccidiag/run
      - run: yarn run test
  machine:
    machine: true
    steps:
      - ccidiag/metricbeat
      - ccidiag/run
      - run: yarn run test
  macos:
    macos:
      xcode: "9.4.0"
    steps:
      - ccidiag/run

workflows:
  version: 2
  main:
    jobs:
      - docker
      - machine
      - macos


