version: 2

orbs:
  ccidiag:
    description: "If you're running this bad things happened"
    commands:
      versions:
        parameters:
          data-dir:
            type: string
            default: "~/.ccidiag"
        steps:
          - run: mkdir << parameters.data-dir >>
          - run: dpkg -l > << parameters.data-dir >>/dpkg.log
          - store_artifacts:
              path: << parameters.data-dir >>
              destination: ccidiag       

jobs:
  run:
    docker:
      - image: buildpack-deps
    steps:
      - ccidiag/versions

workflows:
  version: 2
  main:
    jobs:
      - run


