version: 2

orbs:
  ccidiag:
    description: "If you're running this bad things happened"
    executors:
      default:
        description:
          Uses the basic buildpack-deps image, which has the
          prerequisites for installing heroku's CLI.
        docker:
          - image: buildpack-deps

    commands:
      versions:
        parameters:
          data-dir:
            type: string
            default: "~/.ccidiag"
        steps:
          - run: mkdir << parameters.data-dir >>
          - run: dpkg -l > << parameters.data-dir >>/dpkg.log
          - store_artifacts:
              path: << parameters.data-dir >>
              destination: ccidiag       
    jobs:
      run:
        executor: default
        steps:
          - versions

workflows:
  version: 2
  main:
    jobs:
      - ccidiag/run


